import "../css/app.css";
import "./menu-toggler.js";
import "./modal.js";
import "./anchor-link-smooth.js";
import "./carousel.js";
import "./accordion.js";
import "./slider.js";
import "./shopping-cart.js";
import "./shopping-details.js";
